### ISSUE TITLE
Peer to peer Review October 14th, 2022

### ISSUE THREAD

**Issue by Olivier-Kango** [Nejjari001/To-Do-List-List-structure#8]
#### Good job 👏 
There are some issues that you still need to work on!

![tenor](https://user-images.githubusercontent.com/108806646/191910267-d71bdfd0-091c-487f-ab4d-9ca605350f4a.gif)

## Highlights

✅ Correct use of GitHub workflow
✅ No linter error
✅ README is okay
✅ The project is working 👍 
✅ Good PR description 👍 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

**Comment by Olivier-Kango** [comment]
- [ ]  We noticed that in the README.md file, the live demo link doesn't display the expected page. Kindly try to put /dist at the end of the Link. **https://nejjari001.github.io/To-Do-List-List-structure/dist**,
- [ ] Every time when we reload the page, it displays other items apart from what it should typically show... I suggest verifying the local Storage feature. Maybe data are not stored correctly.

**Comment by Nejjari001** [comment]
Hi @Olivier-Kango, thanks for the review. I will make sure to implement those required changes. Cheers 😃

**Comment by Olivier-Kango** [comment]
Thank you  Bro,
Cheers 🤝
